version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "cron"
      cronjob: "0 2 1 * *"  # 02:00 on the 1st of every month
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 5

    groups:
      github-actions:
        patterns:
          - "*"

    commit-message:
      prefix: "ci"

    labels:
      - "dependencies"
      - "github-actions"
